version: '3.8'

services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    container_name: dynamodb-local
    hostname: dynamodb-local
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  ddmona:
    build: .
    ports:
      - "8090:8080"
